rem C:\PRINTQ\PRINTQ   
PROMPT $p$g
PATH C:\DOS;C:\WINDOWS;C:\DOSRMX;
mkdir d:\temp
SET TEMP=D:\TEMP
rem SET TEMP=C:\DOS
rem c:\dos\print 
rem c:\dosrmx\rmxtsr 
rem c:\dosrmx\loadrmx -n c:\dosrmx\dosrmx -s c_dos -f d 
 
echo *******************************************************************
echo *                                                                 *
echo *     IPSS-Simulator running under "RMX for Windows"  V 2.0       *
echo *                                                                 *
echo *******************************************************************
rem rmxwin 
:end
